import Navigation from './components/Navigation'
import ShopProvider from './context/ShopContext'
import '/src/app/styles/globals.css'

import { Poppins } from 'next/font/google'
const poppins = Poppins({
  weight: ['400', '700', '900'],
  style: 'normal',
  subsets: ['latin'],
  display: 'swap'
})
export const metadata = {
  title: 'Ernesto Serna Cart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ShopProvider>
          <Navigation />
          {children}
        </ShopProvider>
      </body>
    </html>
  )
}
